apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.APP_NAME }}
  namespace: {{ $.Values.NAMESPACE }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.APP_NAME }}
  ports:
    - name: https
      port: {{ .Values.PORT }}
      targetPort: {{ .Values.PORT }}
